package com.woniuxy.cq.soft.entity;

import java.util.Date;

public class Appointment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id_card
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.department
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String beds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.uid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String appointmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.creation_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id
     *
     * @return the value of appointment.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id
     *
     * @param id the value for appointment.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.name
     *
     * @return the value of appointment.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.name
     *
     * @param name the value for appointment.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id_card
     *
     * @return the value of appointment.id_card
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id_card
     *
     * @param idCard the value for appointment.id_card
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.age
     *
     * @return the value of appointment.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.age
     *
     * @param age the value for appointment.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.sex
     *
     * @return the value of appointment.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.sex
     *
     * @param sex the value for appointment.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.department
     *
     * @return the value of appointment.department
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.department
     *
     * @param department the value for appointment.department
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.beds
     *
     * @return the value of appointment.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getBeds() {
        return beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.beds
     *
     * @param beds the value for appointment.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setBeds(String beds) {
        this.beds = beds == null ? null : beds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.phone
     *
     * @return the value of appointment.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.phone
     *
     * @param phone the value for appointment.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.uid
     *
     * @return the value of appointment.uid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.uid
     *
     * @param uid the value for appointment.uid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.status
     *
     * @return the value of appointment.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.status
     *
     * @param status the value for appointment.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_time
     *
     * @return the value of appointment.appointment_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_time
     *
     * @param appointmentTime the value for appointment.appointment_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setAppointmentTime(String appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.creation_time
     *
     * @return the value of appointment.creation_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.creation_time
     *
     * @param creationTime the value for appointment.creation_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setCreationTime(String creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", idCard=").append(idCard);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", department=").append(department);
        sb.append(", beds=").append(beds);
        sb.append(", phone=").append(phone);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", appointmentTime=").append(appointmentTime);
        sb.append(", creationTime=").append(creationTime);
        sb.append("]");
        return sb.toString();
    }
}