package com.woniuxy.cq.soft.entity;

public class Beds {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beds.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beds.room
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beds.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String beds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beds.depid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer depid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beds.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beds.id
     *
     * @return the value of beds.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beds.id
     *
     * @param id the value for beds.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beds.room
     *
     * @return the value of beds.room
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beds.room
     *
     * @param room the value for beds.room
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beds.beds
     *
     * @return the value of beds.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getBeds() {
        return beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beds.beds
     *
     * @param beds the value for beds.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setBeds(String beds) {
        this.beds = beds == null ? null : beds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beds.depid
     *
     * @return the value of beds.depid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beds.depid
     *
     * @param depid the value for beds.depid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDepid(Integer depid) {
        this.depid = depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beds.status
     *
     * @return the value of beds.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beds.status
     *
     * @param status the value for beds.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", room=").append(room);
        sb.append(", beds=").append(beds);
        sb.append(", depid=").append(depid);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}