package com.woniuxy.cq.soft.entity;

import java.util.ArrayList;
import java.util.List;

public class ConsultationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public ConsultationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Integer value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Integer value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Integer value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Integer value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Integer value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Integer value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Integer> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Integer> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Integer value1, Integer value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Integer value1, Integer value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andPaidIsNull() {
            addCriterion("paid is null");
            return (Criteria) this;
        }

        public Criteria andPaidIsNotNull() {
            addCriterion("paid is not null");
            return (Criteria) this;
        }

        public Criteria andPaidEqualTo(Integer value) {
            addCriterion("paid =", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotEqualTo(Integer value) {
            addCriterion("paid <>", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidGreaterThan(Integer value) {
            addCriterion("paid >", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("paid >=", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidLessThan(Integer value) {
            addCriterion("paid <", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidLessThanOrEqualTo(Integer value) {
            addCriterion("paid <=", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidIn(List<Integer> values) {
            addCriterion("paid in", values, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotIn(List<Integer> values) {
            addCriterion("paid not in", values, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidBetween(Integer value1, Integer value2) {
            addCriterion("paid between", value1, value2, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotBetween(Integer value1, Integer value2) {
            addCriterion("paid not between", value1, value2, "paid");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusIsNull() {
            addCriterion("consultation_status is null");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusIsNotNull() {
            addCriterion("consultation_status is not null");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusEqualTo(String value) {
            addCriterion("consultation_status =", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusNotEqualTo(String value) {
            addCriterion("consultation_status <>", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusGreaterThan(String value) {
            addCriterion("consultation_status >", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusGreaterThanOrEqualTo(String value) {
            addCriterion("consultation_status >=", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusLessThan(String value) {
            addCriterion("consultation_status <", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusLessThanOrEqualTo(String value) {
            addCriterion("consultation_status <=", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusLike(String value) {
            addCriterion("consultation_status like", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusNotLike(String value) {
            addCriterion("consultation_status not like", value, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusIn(List<String> values) {
            addCriterion("consultation_status in", values, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusNotIn(List<String> values) {
            addCriterion("consultation_status not in", values, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusBetween(String value1, String value2) {
            addCriterion("consultation_status between", value1, value2, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andConsultationStatusNotBetween(String value1, String value2) {
            addCriterion("consultation_status not between", value1, value2, "consultationStatus");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andPatientStatusIsNull() {
            addCriterion("patient_status is null");
            return (Criteria) this;
        }

        public Criteria andPatientStatusIsNotNull() {
            addCriterion("patient_status is not null");
            return (Criteria) this;
        }

        public Criteria andPatientStatusEqualTo(String value) {
            addCriterion("patient_status =", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusNotEqualTo(String value) {
            addCriterion("patient_status <>", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusGreaterThan(String value) {
            addCriterion("patient_status >", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusGreaterThanOrEqualTo(String value) {
            addCriterion("patient_status >=", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusLessThan(String value) {
            addCriterion("patient_status <", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusLessThanOrEqualTo(String value) {
            addCriterion("patient_status <=", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusLike(String value) {
            addCriterion("patient_status like", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusNotLike(String value) {
            addCriterion("patient_status not like", value, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusIn(List<String> values) {
            addCriterion("patient_status in", values, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusNotIn(List<String> values) {
            addCriterion("patient_status not in", values, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusBetween(String value1, String value2) {
            addCriterion("patient_status between", value1, value2, "patientStatus");
            return (Criteria) this;
        }

        public Criteria andPatientStatusNotBetween(String value1, String value2) {
            addCriterion("patient_status not between", value1, value2, "patientStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consultation
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 16 11:11:27 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}