package com.woniuxy.cq.soft.entity;

public class Consultation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consultation.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consultation.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consultation.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consultation.consultation_status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String consultationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consultation.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consultation.patient_status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String patientStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consultation.id
     *
     * @return the value of consultation.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consultation.id
     *
     * @param id the value for consultation.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consultation.eid
     *
     * @return the value of consultation.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consultation.eid
     *
     * @param eid the value for consultation.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consultation.paid
     *
     * @return the value of consultation.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consultation.paid
     *
     * @param paid the value for consultation.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consultation.consultation_status
     *
     * @return the value of consultation.consultation_status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getConsultationStatus() {
        return consultationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consultation.consultation_status
     *
     * @param consultationStatus the value for consultation.consultation_status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setConsultationStatus(String consultationStatus) {
        this.consultationStatus = consultationStatus == null ? null : consultationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consultation.note
     *
     * @return the value of consultation.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consultation.note
     *
     * @param note the value for consultation.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consultation.patient_status
     *
     * @return the value of consultation.patient_status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getPatientStatus() {
        return patientStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consultation.patient_status
     *
     * @param patientStatus the value for consultation.patient_status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPatientStatus(String patientStatus) {
        this.patientStatus = patientStatus == null ? null : patientStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", paid=").append(paid);
        sb.append(", consultationStatus=").append(consultationStatus);
        sb.append(", note=").append(note);
        sb.append(", patientStatus=").append(patientStatus);
        sb.append("]");
        return sb.toString();
    }
}