package com.woniuxy.cq.soft.entity;

public class DoctorAdviceDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.did
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.drug_name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String drugName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.number
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.price
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice_details.type
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.id
     *
     * @return the value of doctor_advice_details.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.id
     *
     * @param id the value for doctor_advice_details.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.did
     *
     * @return the value of doctor_advice_details.did
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.did
     *
     * @param did the value for doctor_advice_details.did
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.drug_name
     *
     * @return the value of doctor_advice_details.drug_name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.drug_name
     *
     * @param drugName the value for doctor_advice_details.drug_name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.number
     *
     * @return the value of doctor_advice_details.number
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.number
     *
     * @param number the value for doctor_advice_details.number
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.price
     *
     * @return the value of doctor_advice_details.price
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.price
     *
     * @param price the value for doctor_advice_details.price
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.note
     *
     * @return the value of doctor_advice_details.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.note
     *
     * @param note the value for doctor_advice_details.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.status
     *
     * @return the value of doctor_advice_details.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.status
     *
     * @param status the value for doctor_advice_details.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice_details.type
     *
     * @return the value of doctor_advice_details.type
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice_details.type
     *
     * @param type the value for doctor_advice_details.type
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", did=").append(did);
        sb.append(", drugName=").append(drugName);
        sb.append(", number=").append(number);
        sb.append(", price=").append(price);
        sb.append(", note=").append(note);
        sb.append(", status=").append(status);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }
}