package com.woniuxy.cq.soft.entity;

public class DoctorAdvice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_advice.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice.id
     *
     * @return the value of doctor_advice.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice.id
     *
     * @param id the value for doctor_advice.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice.eid
     *
     * @return the value of doctor_advice.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice.eid
     *
     * @param eid the value for doctor_advice.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice.paid
     *
     * @return the value of doctor_advice.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice.paid
     *
     * @param paid the value for doctor_advice.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_advice.status
     *
     * @return the value of doctor_advice.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_advice.status
     *
     * @param status the value for doctor_advice.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", paid=").append(paid);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}