package com.woniuxy.cq.soft.entity;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.password
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.rid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.did
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.phone
     *
     * @return the value of employees.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.phone
     *
     * @param phone the value for employees.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.password
     *
     * @return the value of employees.password
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.password
     *
     * @param password the value for employees.password
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.name
     *
     * @return the value of employees.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.name
     *
     * @param name the value for employees.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.age
     *
     * @return the value of employees.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.age
     *
     * @param age the value for employees.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.sex
     *
     * @return the value of employees.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.sex
     *
     * @param sex the value for employees.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.rid
     *
     * @return the value of employees.rid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.rid
     *
     * @param rid the value for employees.rid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.did
     *
     * @return the value of employees.did
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.did
     *
     * @param did the value for employees.did
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.status
     *
     * @return the value of employees.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.status
     *
     * @param status the value for employees.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employees
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", rid=").append(rid);
        sb.append(", did=").append(did);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}