package com.woniuxy.cq.soft.entity;

import java.util.Date;

public class MoneyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_detail.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_detail.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_detail.detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_detail.time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_detail.patid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer patid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money_detail.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_detail.id
     *
     * @return the value of money_detail.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_detail.id
     *
     * @param id the value for money_detail.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_detail.money
     *
     * @return the value of money_detail.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_detail.money
     *
     * @param money the value for money_detail.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_detail.detail
     *
     * @return the value of money_detail.detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_detail.detail
     *
     * @param detail the value for money_detail.detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_detail.time
     *
     * @return the value of money_detail.time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_detail.time
     *
     * @param time the value for money_detail.time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_detail.patid
     *
     * @return the value of money_detail.patid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getPatid() {
        return patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_detail.patid
     *
     * @param patid the value for money_detail.patid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPatid(Integer patid) {
        this.patid = patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money_detail.status
     *
     * @return the value of money_detail.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money_detail.status
     *
     * @param status the value for money_detail.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table money_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", money=").append(money);
        sb.append(", detail=").append(detail);
        sb.append(", time=").append(time);
        sb.append(", patid=").append(patid);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}