package com.woniuxy.cq.soft.entity;

import java.util.Date;

public class Nursing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.nursing_type
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String nursingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.nursing_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String nursingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.nursing_record
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String nursingRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.id
     *
     * @return the value of nursing.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.id
     *
     * @param id the value for nursing.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.eid
     *
     * @return the value of nursing.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.eid
     *
     * @param eid the value for nursing.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.paid
     *
     * @return the value of nursing.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.paid
     *
     * @param paid the value for nursing.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.nursing_type
     *
     * @return the value of nursing.nursing_type
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getNursingType() {
        return nursingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.nursing_type
     *
     * @param nursingType the value for nursing.nursing_type
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNursingType(String nursingType) {
        this.nursingType = nursingType == null ? null : nursingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.nursing_time
     *
     * @return the value of nursing.nursing_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getNursingTime() {
        return nursingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.nursing_time
     *
     * @param nursingTime the value for nursing.nursing_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNursingTime(String nursingTime) {
        this.nursingTime = nursingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.nursing_record
     *
     * @return the value of nursing.nursing_record
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getNursingRecord() {
        return nursingRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.nursing_record
     *
     * @param nursingRecord the value for nursing.nursing_record
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNursingRecord(String nursingRecord) {
        this.nursingRecord = nursingRecord == null ? null : nursingRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing.status
     *
     * @return the value of nursing.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing.status
     *
     * @param status the value for nursing.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", paid=").append(paid);
        sb.append(", nursingType=").append(nursingType);
        sb.append(", nursingTime=").append(nursingTime);
        sb.append(", nursingRecord=").append(nursingRecord);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}