package com.woniuxy.cq.soft.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NursingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public NursingExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Integer value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Integer value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Integer value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Integer value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Integer value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Integer value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Integer> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Integer> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Integer value1, Integer value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Integer value1, Integer value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andPaidIsNull() {
            addCriterion("paid is null");
            return (Criteria) this;
        }

        public Criteria andPaidIsNotNull() {
            addCriterion("paid is not null");
            return (Criteria) this;
        }

        public Criteria andPaidEqualTo(Integer value) {
            addCriterion("paid =", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotEqualTo(Integer value) {
            addCriterion("paid <>", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidGreaterThan(Integer value) {
            addCriterion("paid >", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("paid >=", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidLessThan(Integer value) {
            addCriterion("paid <", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidLessThanOrEqualTo(Integer value) {
            addCriterion("paid <=", value, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidIn(List<Integer> values) {
            addCriterion("paid in", values, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotIn(List<Integer> values) {
            addCriterion("paid not in", values, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidBetween(Integer value1, Integer value2) {
            addCriterion("paid between", value1, value2, "paid");
            return (Criteria) this;
        }

        public Criteria andPaidNotBetween(Integer value1, Integer value2) {
            addCriterion("paid not between", value1, value2, "paid");
            return (Criteria) this;
        }

        public Criteria andNursingTypeIsNull() {
            addCriterion("nursing_type is null");
            return (Criteria) this;
        }

        public Criteria andNursingTypeIsNotNull() {
            addCriterion("nursing_type is not null");
            return (Criteria) this;
        }

        public Criteria andNursingTypeEqualTo(String value) {
            addCriterion("nursing_type =", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeNotEqualTo(String value) {
            addCriterion("nursing_type <>", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeGreaterThan(String value) {
            addCriterion("nursing_type >", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("nursing_type >=", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeLessThan(String value) {
            addCriterion("nursing_type <", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeLessThanOrEqualTo(String value) {
            addCriterion("nursing_type <=", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeLike(String value) {
            addCriterion("nursing_type like", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeNotLike(String value) {
            addCriterion("nursing_type not like", value, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeIn(List<String> values) {
            addCriterion("nursing_type in", values, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeNotIn(List<String> values) {
            addCriterion("nursing_type not in", values, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeBetween(String value1, String value2) {
            addCriterion("nursing_type between", value1, value2, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTypeNotBetween(String value1, String value2) {
            addCriterion("nursing_type not between", value1, value2, "nursingType");
            return (Criteria) this;
        }

        public Criteria andNursingTimeIsNull() {
            addCriterion("nursing_time is null");
            return (Criteria) this;
        }

        public Criteria andNursingTimeIsNotNull() {
            addCriterion("nursing_time is not null");
            return (Criteria) this;
        }

        public Criteria andNursingTimeEqualTo(Date value) {
            addCriterion("nursing_time =", value, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeNotEqualTo(Date value) {
            addCriterion("nursing_time <>", value, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeGreaterThan(Date value) {
            addCriterion("nursing_time >", value, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("nursing_time >=", value, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeLessThan(Date value) {
            addCriterion("nursing_time <", value, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeLessThanOrEqualTo(Date value) {
            addCriterion("nursing_time <=", value, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeIn(List<Date> values) {
            addCriterion("nursing_time in", values, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeNotIn(List<Date> values) {
            addCriterion("nursing_time not in", values, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeBetween(Date value1, Date value2) {
            addCriterion("nursing_time between", value1, value2, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingTimeNotBetween(Date value1, Date value2) {
            addCriterion("nursing_time not between", value1, value2, "nursingTime");
            return (Criteria) this;
        }

        public Criteria andNursingRecordIsNull() {
            addCriterion("nursing_record is null");
            return (Criteria) this;
        }

        public Criteria andNursingRecordIsNotNull() {
            addCriterion("nursing_record is not null");
            return (Criteria) this;
        }

        public Criteria andNursingRecordEqualTo(String value) {
            addCriterion("nursing_record =", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordNotEqualTo(String value) {
            addCriterion("nursing_record <>", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordGreaterThan(String value) {
            addCriterion("nursing_record >", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordGreaterThanOrEqualTo(String value) {
            addCriterion("nursing_record >=", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordLessThan(String value) {
            addCriterion("nursing_record <", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordLessThanOrEqualTo(String value) {
            addCriterion("nursing_record <=", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordLike(String value) {
            addCriterion("nursing_record like", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordNotLike(String value) {
            addCriterion("nursing_record not like", value, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordIn(List<String> values) {
            addCriterion("nursing_record in", values, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordNotIn(List<String> values) {
            addCriterion("nursing_record not in", values, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordBetween(String value1, String value2) {
            addCriterion("nursing_record between", value1, value2, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andNursingRecordNotBetween(String value1, String value2) {
            addCriterion("nursing_record not between", value1, value2, "nursingRecord");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nursing
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 16 11:11:27 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}