package com.woniuxy.cq.soft.entity;

public class OutHospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_hospital.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_hospital.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_hospital.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_hospital.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_hospital.paname
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String paname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_hospital.id
     *
     * @return the value of out_hospital.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_hospital.id
     *
     * @param id the value for out_hospital.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_hospital.eid
     *
     * @return the value of out_hospital.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_hospital.eid
     *
     * @param eid the value for out_hospital.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_hospital.paid
     *
     * @return the value of out_hospital.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_hospital.paid
     *
     * @param paid the value for out_hospital.paid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_hospital.status
     *
     * @return the value of out_hospital.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_hospital.status
     *
     * @param status the value for out_hospital.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_hospital.paname
     *
     * @return the value of out_hospital.paname
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getPaname() {
        return paname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_hospital.paname
     *
     * @param paname the value for out_hospital.paname
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPaname(String paname) {
        this.paname = paname == null ? null : paname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", paid=").append(paid);
        sb.append(", status=").append(status);
        sb.append(", paname=").append(paname);
        sb.append("]");
        return sb.toString();
    }
}