package com.woniuxy.cq.soft.entity;

import java.util.Date;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.id_card
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.department
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String beds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.uid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.creation_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.dateil
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String dateil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.ename
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.emid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer emid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.emname
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String emname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.id
     *
     * @return the value of patient.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.id
     *
     * @param id the value for patient.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.name
     *
     * @return the value of patient.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.name
     *
     * @param name the value for patient.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.id_card
     *
     * @return the value of patient.id_card
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.id_card
     *
     * @param idCard the value for patient.id_card
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.age
     *
     * @return the value of patient.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.age
     *
     * @param age the value for patient.age
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.sex
     *
     * @return the value of patient.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.sex
     *
     * @param sex the value for patient.sex
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.department
     *
     * @return the value of patient.department
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.department
     *
     * @param department the value for patient.department
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.beds
     *
     * @return the value of patient.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getBeds() {
        return beds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.beds
     *
     * @param beds the value for patient.beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setBeds(String beds) {
        this.beds = beds == null ? null : beds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.phone
     *
     * @return the value of patient.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.phone
     *
     * @param phone the value for patient.phone
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.uid
     *
     * @return the value of patient.uid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.uid
     *
     * @param uid the value for patient.uid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.status
     *
     * @return the value of patient.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.status
     *
     * @param status the value for patient.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.creation_time
     *
     * @return the value of patient.creation_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.creation_time
     *
     * @param creationTime the value for patient.creation_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.dateil
     *
     * @return the value of patient.dateil
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getDateil() {
        return dateil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.dateil
     *
     * @param dateil the value for patient.dateil
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDateil(String dateil) {
        this.dateil = dateil == null ? null : dateil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.money
     *
     * @return the value of patient.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.money
     *
     * @param money the value for patient.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.eid
     *
     * @return the value of patient.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.eid
     *
     * @param eid the value for patient.eid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.ename
     *
     * @return the value of patient.ename
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.ename
     *
     * @param ename the value for patient.ename
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.emid
     *
     * @return the value of patient.emid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getEmid() {
        return emid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.emid
     *
     * @param emid the value for patient.emid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEmid(Integer emid) {
        this.emid = emid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.emname
     *
     * @return the value of patient.emname
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getEmname() {
        return emname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.emname
     *
     * @param emname the value for patient.emname
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setEmname(String emname) {
        this.emname = emname == null ? null : emname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", idCard=").append(idCard);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", department=").append(department);
        sb.append(", beds=").append(beds);
        sb.append(", phone=").append(phone);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", creationTime=").append(creationTime);
        sb.append(", dateil=").append(dateil);
        sb.append(", money=").append(money);
        sb.append(", eid=").append(eid);
        sb.append(", ename=").append(ename);
        sb.append(", emid=").append(emid);
        sb.append(", emname=").append(emname);
        sb.append("]");
        return sb.toString();
    }
}