package com.woniuxy.cq.soft.entity;

import java.util.Date;

public class RefundDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.ddid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer ddid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.number
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_details.creat_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    private Date creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.id
     *
     * @return the value of refund_details.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.id
     *
     * @param id the value for refund_details.id
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.ddid
     *
     * @return the value of refund_details.ddid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getDdid() {
        return ddid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.ddid
     *
     * @param ddid the value for refund_details.ddid
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setDdid(Integer ddid) {
        this.ddid = ddid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.name
     *
     * @return the value of refund_details.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.name
     *
     * @param name the value for refund_details.name
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.number
     *
     * @return the value of refund_details.number
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.number
     *
     * @param number the value for refund_details.number
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.money
     *
     * @return the value of refund_details.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.money
     *
     * @param money the value for refund_details.money
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.note
     *
     * @return the value of refund_details.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.note
     *
     * @param note the value for refund_details.note
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.status
     *
     * @return the value of refund_details.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.status
     *
     * @param status the value for refund_details.status
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_details.creat_time
     *
     * @return the value of refund_details.creat_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_details.creat_time
     *
     * @param creatTime the value for refund_details.creat_time
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ddid=").append(ddid);
        sb.append(", name=").append(name);
        sb.append(", number=").append(number);
        sb.append(", money=").append(money);
        sb.append(", note=").append(note);
        sb.append(", status=").append(status);
        sb.append(", creatTime=").append(creatTime);
        sb.append("]");
        return sb.toString();
    }
}