package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.Beds;
import com.woniuxy.cq.soft.entity.BedsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BedsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(BedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(BedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(Beds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(Beds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<Beds> selectByExample(BedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    Beds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") Beds record, @Param("example") BedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") Beds record, @Param("example") BedsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(Beds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beds
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(Beds record);
    List<Beds> selectDepartByName(String name);
}