package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.Consultation;
import com.woniuxy.cq.soft.entity.ConsultationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsultationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(ConsultationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(ConsultationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<Consultation> selectByExample(ConsultationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    Consultation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") Consultation record, @Param("example") ConsultationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") Consultation record, @Param("example") ConsultationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(Consultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consultation
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(Consultation record);
}