package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.DoctorAdviceDetails;
import com.woniuxy.cq.soft.entity.DoctorAdviceDetailsExample;

import java.sql.ClientInfoStatus;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import javax.swing.*;

public interface DoctorAdviceDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(DoctorAdviceDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(DoctorAdviceDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(DoctorAdviceDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(DoctorAdviceDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<DoctorAdviceDetails> selectByExample(DoctorAdviceDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    DoctorAdviceDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") DoctorAdviceDetails record, @Param("example") DoctorAdviceDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") DoctorAdviceDetails record, @Param("example") DoctorAdviceDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(DoctorAdviceDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(DoctorAdviceDetails record);

    //新增多条记录
    void insertAdvices(List<DoctorAdviceDetails> list);

    //查询多条记录
    List<DoctorAdviceDetails> selectDoctorAdvice(Integer eid,Integer status);


    List<Map> queryAoctorAdvice(@Param("name")String name, @Param("id")int id);
}