package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.DoctorAdvice;
import com.woniuxy.cq.soft.entity.DoctorAdviceExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DoctorAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(DoctorAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(DoctorAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(DoctorAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(DoctorAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<DoctorAdvice> selectByExample(DoctorAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    DoctorAdvice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") DoctorAdvice record, @Param("example") DoctorAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") DoctorAdvice record, @Param("example") DoctorAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(DoctorAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_advice
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(DoctorAdvice record);
    List<Map<String,Object>> selectMedicalByPaid(Integer paid);
}