package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.DrugRecords;
import com.woniuxy.cq.soft.entity.DrugRecordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrugRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(DrugRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(DrugRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(DrugRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(DrugRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<DrugRecords> selectByExample(DrugRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    DrugRecords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") DrugRecords record, @Param("example") DrugRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") DrugRecords record, @Param("example") DrugRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(DrugRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_records
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(DrugRecords record);
}