package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.Nursing;
import com.woniuxy.cq.soft.entity.NursingExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface NursingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(NursingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(NursingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(Nursing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(Nursing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<Nursing> selectByExample(NursingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    Nursing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") Nursing record, @Param("example") NursingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") Nursing record, @Param("example") NursingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(Nursing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(Nursing record);
    List<Map<String,Object>> selectNursings(Integer eid);

}