package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.OutHospital;
import com.woniuxy.cq.soft.entity.OutHospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutHospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(OutHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(OutHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(OutHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(OutHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<OutHospital> selectByExample(OutHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    OutHospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") OutHospital record, @Param("example") OutHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") OutHospital record, @Param("example") OutHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(OutHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_hospital
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(OutHospital record);
}