package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.PatDetail;
import com.woniuxy.cq.soft.entity.PatDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(PatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(PatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(PatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(PatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<PatDetail> selectByExample(PatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    PatDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") PatDetail record, @Param("example") PatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") PatDetail record, @Param("example") PatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(PatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_detail
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(PatDetail record);
}