package com.woniuxy.cq.soft.mapper;

import com.woniuxy.cq.soft.entity.RefundDetails;
import com.woniuxy.cq.soft.entity.RefundDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    long countByExample(RefundDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByExample(RefundDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insert(RefundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int insertSelective(RefundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    List<RefundDetails> selectByExample(RefundDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    RefundDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") RefundDetails record, @Param("example") RefundDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByExample(@Param("record") RefundDetails record, @Param("example") RefundDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKeySelective(RefundDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_details
     *
     * @mbg.generated Fri Oct 16 11:11:27 CST 2020
     */
    int updateByPrimaryKey(RefundDetails record);
}